---
firewalld_extra_allow_ports:
  - "22/tcp"
  - "80/tcp"
  - "443/tcp"

gitea_version: 1.21.11
gitea_database: mysql
gitea_hostname: git.almalinux.org

mysql_root_password:
  "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/infra/{% if staging %}stg/{% endif %}gitea:mysql_root_password',
  token=lookup('env', 'VAULT_TOKEN'), url=secrets_url) }}"
mysql_databases:
  - name: gitea
mysql_users:
  - name: gitea
    password:
      "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/infra/{% if staging %}stg/{% endif %}gitea:mysql_gitea_user_password',
      token=lookup('env', 'VAULT_TOKEN'), url=secrets_url) }}"
    priv: gitea.*:ALL
mysql_innodb_buffer_pool_size: "2G"
mysql_innodb_log_file_size: "512M"
mysql_innodb_log_buffer_size: "128M"
mysql_query_cache_size: "0"
mysql_key_buffer_size: "0"
mysql_sort_buffer_size: 2097152
mysql_read_buffer_size: 131072
mysql_read_rnd_buffer_size: 262144
mysql_myisam_sort_buffer_size: "0"
mysql_join_buffer_size: 262144

gitea_config:
  no_section:
    APP_NAME: AlmaLinux OS Foundation Git Server
    RUN_MODE: prod
    RUN_USER: git
    WORK_PATH: /var/lib/gitea
  sections:
    database:
      DB_TYPE: mysql
      HOST: /var/lib/mysql/mysql.sock
      NAME: gitea
      USER: gitea
      PASSWD:
        "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/infra/{% if staging %}stg/{% endif %}gitea:mysql_gitea_user_password',
        token=lookup('env', 'VAULT_TOKEN'), url=secrets_url) }}"
      LOG_SQL: "false"
      SSL_MODE: disable
      CHARSET: utf8
    server:
      ROOT_URL: https://{{ gitea_hostname }}
      APP_DATA_PATH: /var/lib/gitea/data
      DOMAIN: "{{ gitea_hostname }}"
      SSH_DOMAIN: "{{ gitea_hostname }}"
      HTTP_PORT: 3000
      DISABLE_SSH: "false"
      SSH_PORT: 22
      SSH_LISTEN_PORT: 22
      OFFLINE_MODE: "false"
      LANDING_PAGE: explore
    repository:
      ROOT: /var/lib/gitea/data/repositories
      DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls
    indexer:
      ISSUE_INDEXER_PATH: /var/lib/gitea/indexers/issues.bleve
    lfs:
      PATH: /var/lib/gitea/data/lfs
    mailer:
      ENABLED: "false"
    service:
      REGISTER_EMAIL_CONFIRM: "false"
      ENABLE_NOTIFY_MAIL: "false"
      DISABLE_REGISTRATION: "false"
      ALLOW_ONLY_EXTERNAL_REGISTRATION: "true"
      ENABLE_CAPTCHA: "false"
      REQUIRE_SIGNIN_VIEW: "false"
      DEFAULT_KEEP_EMAIL_PRIVATE: "false"
      DEFAULT_ALLOW_CREATE_ORGANIZATION: "true"
      DEFAULT_ENABLE_TIMETRACKING: "true"
      NO_REPLY_ADDRESS: noreply.localhost
    openid:
      ENABLE_OPENID_SIGNIN: "true"
      ENABLE_OPENID_SIGNUP: "true"
    cron.update_checker:
      ENABLED: "false"
    session:
      PROVIDER: file
    log:
      MODE: console
      LEVEL: info
      ROOT_PATH: /var/lib/gitea/log
    security:
      INSTALL_LOCK: "true"
      REVERSE_PROXY_LIMIT: 1
      REVERSE_PROXY_TRUSTED_PROXIES: "*"
      PASSWORD_HASH_ALGO: pbkdf2
      SECRET_KEY:
        "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/infra/{% if staging %}stg/{% endif %}gitea:secret_key',
        token=lookup('env', 'VAULT_TOKEN'), url=secrets_url) }}"
      INTERNAL_TOKEN:
        "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/infra/{% if staging %}stg/{% endif %}gitea:internal_token',
        token=lookup('env', 'VAULT_TOKEN'), url=secrets_url) }}"
    oauth2:
      JWT_SECRET:
        "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/infra/{% if staging %}stg/{% endif %}gitea:jwt_secret',
        token=lookup('env', 'VAULT_TOKEN'), url=secrets_url) }}"
    log.file:
      LOG_ROTATE: "true"
      MAX_SIZE_SHIFT: 28
      DAILY_ROTATE: "true"
      MAX_DAYS: 31
      COMPRESS: "true"
    repository.pull_request:
      DEFAULT_MERGE_STYLE: merge
    repository.signing:
      DEFAULT_TRUST_MODEL: committer
    repository.local:
      LOCAL_COPY_PATH: /var/lib/gitea/tmp/local-repo
    repository.upload:
      TEMP_PATH: /var/lib/gitea/uploads
    picture:
      AVATAR_UPLOAD_PATH: /var/lib/gitea/data/avatars
      REPOSITORY_AVATAR_UPLOAD_PATH: /var/lib/gitea/data/repo-avatars
      DISABLE_GRAVATAR: "false"
    cron.archive_cleanup:
      ENABLED: "true"
      SHCEDULE: "@midnight"
      OLDER_THAN: 24h
    webhook:
      DELIVER_TIMEOUT: 300
