---
# handlers file for pinnwand
- name: Reload httpd webserver
  ansible.builtin.systemd:
    name: httpd
    state: reloaded

- name: Start pinnwand service
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: pinnwand
    state: started
