---
- name: Install caddy copr repo
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: "@caddy/caddy"
    chroot: epel-10-aarch64

- name: Install caddy
  ansible.builtin.package:
    name: caddy
    state: present

- name: Enable caddy
  ansible.builtin.service:
    name: caddy
    enabled: true

- name: Upload caddy config
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: '0700'
    owner: caddy
    group: caddy
  notify: Restart caddy

- name: Set httpd_unified
  ansible.posix.seboolean:
    name: httpd_unified
    state: true
    persistent: true
