---
- name: Install Valkey
  ansible.builtin.dnf:
    name: valkey
    state: present
  tags:
    - valkey

- name: Start/enable Valkey
  ansible.builtin.systemd_service:
    name: valkey.service
    state: started
    enabled: true
  tags:
    - valkey
