---
- name: Install podman
  ansible.builtin.package:
    name: podman
    state: present

- name: Create a podman network
  containers.podman.podman_network:
    name: podman_network

- name: Create persistent mariadb container directory
  ansible.builtin.file:
    path: /opt/mariadb
    state: directory
    owner: 1001
    group: 1001
    mode: '0700'
  register: keycloak_create_opt_mariadb

- name: Set SELinux context for container's directory
  community.general.sefcontext:
    target: '/opt/mariadb(/.*)?'
    setype: container_file_t
    state: present
  register: keycloak_set_selinux_context

# need to apply new contexts "now" to prevent potential issues in later tasks
- name: Apply new SELinux file context to filesystem # noqa no-handler no-changed-when
  ansible.builtin.command: restorecon -irv /opt/mariadb
  when: keycloak_set_selinux_context.changed or keycloak_create_opt_mariadb.changed
