---
collections:
    - name: ansible.posix
    - name: devsec.hardening
    - name: freeipa.ansible_freeipa
    - name: community.hashi_vault
    - name: community.zabbix
    - name: community.general

roles:
    - name: artis3n.tailscale
    - name: ansible-modules-hashivault
      src: git+https://github.com/TerryHowe/ansible-modules-hashivault.git
    - name: geerlingguy.postgresql
