---
- name: Install Caddy
  ansible.builtin.dnf:
    name: caddy
    state: present
  tags:
    - caddy

- name: Create Caddy log dir
  ansible.builtin.file:
    path: /var/log/caddy/
    owner: caddy
    group: caddy
    mode: "0700"
    state: directory
  tags:
    - caddy

- name: Set SELinux context for log directory
  community.general.sefcontext:
    target: '/var/log/caddy(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  register: set_selinux_context

# need to apply new contexts "now" to prevent potential issues in later tasks
- name: Apply new SELinux file context to filesystem # noqa no-handler no-changed-when
  ansible.builtin.command: restorecon -irv /var/log/caddy
  when: set_selinux_context.changed

- name: Distribute /etc/caddy/Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0600"
    owner: caddy
    group: caddy
  notify: Restart caddy
  tags:
    - caddy

- name: Allow binding ports in selinux
  community.general.seport:
    ports: 8448
    proto: "{{ item }}"
    setype: http_port_t
    state: present
  loop:
    - tcp
    - udp

- name: Start and enable Caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: started
    enabled: true
  tags:
    - caddy
