---
mirror_custom_ssl: false
mirror_path: /mirror
# use a /almalinux subdir within mirror_path if true
mirror_path_use_subdir: true

# inspiration from https://github.com/PhirePhly/micromirrors/blob/main/files/sysctl.performancetune.conf
mirror_sysctl_performance:
  - name: net.core.default_qdisc
    value: fq_codel
  - name: net.ipv4.tcp_congestion_control
    value: bbr
  - name: net.core.rmem_max
    value: 134217728
  - name: net.core.wmem_max
    value: 134217728
  - name: net.ipv4.tcp_rmem
    value: 4096 87380 67108864
  - name: net.ipv4.tcp_wmem
    value: 4096 87380 67108864
  - name: net.ipv4.tcp_mtu_probing
    value: 1
  - name: net.ipv4.tcp_fastopen
    value: 1
  - name: net.ipv4.tcp_no_metrics_save
    value: 1
  - name: net.ipv4.tcp_slow_start_after_idle
    value: 0
  - name: net.ipv4.tcp_notsent_lowat
    value: 1048576

mirror_create_fs: true

mirror_enable_http: true

mirror_repos:
  - mirror_name: almalinux
    bootstrap_command:
      "/usr/bin/rsync -avSH --exclude='.~tmp~' rsync://rsync.repo.almalinux.org/almalinux/TIME
      {{ mirror_path }}{% if mirror_path_use_subdir %}/almalinux/{% endif %}"
    creates: "{{ mirror_path }}{% if mirror_path_use_subdir %}/almalinux{% endif %}/TIME"
    rsync_command:
      "sleep $(((RANDOM\\%3500)+1)) && /usr/bin/flock -n /var/run/almalinux_rsync.lock -c
      \"/usr/bin/rsync -avSH --exclude='.~tmp~' --delete-delay --delay-updates
      rsync://rsync.repo.almalinux.org/almalinux/ {{ mirror_path }}{% if mirror_path_use_subdir %}/almalinux/{% endif %}\""
    rsync_name: mirror_rsync
    rsync_user: root
    rsync_minute: "0"
    rsync_hour: "*/1"
    rsync_file: almalinux_rsync
