---
- name: Install Caddy
  ansible.builtin.dnf:
    name: caddy
    state: present
  tags:
    - caddy

- name: Create Caddy log dir
  ansible.builtin.file:
    path: /var/log/caddy/
    owner: caddy
    group: caddy
    mode: "0700"
    state: directory
  tags:
    - caddy

- name: Set SELinux context for log directory
  community.general.sefcontext:
    target: '/var/log/caddy(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  register: set_selinux_context
  tags:
    - caddy

# need to apply new contexts "now" to prevent potential issues in later tasks
- name: Apply new SELinux file context to filesystem # noqa no-handler no-changed-when
  ansible.builtin.command: restorecon -irv /var/log/caddy
  when: set_selinux_context.changed
  tags:
    - caddy

- name: Distribute /etc/caddy/Caddyfile
  ansible.builtin.template:
    src: etc/caddy/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0600"
    owner: caddy
    group: caddy
  notify: Restart caddy
  tags:
    - caddy

- name: Allow http/https/ssh traffic through firewalld
  ansible.posix.firewalld:
    zone: public
    state: enabled
    permanent: true
    immediate: true
    service: "{{ item }}"
  loop:
    - http
    - https
    - ssh
  tags:
    - firewalld

- name: Create mirror directory
  ansible.builtin.file:
    path: "{{ mirror_path }}"
    state: directory
    mode: "0755"
  tags:
    - bootstrap_mirror

- name: Set SELinux context for mirror directory
  community.general.sefcontext:
    target: '{{ mirror_path }}(/.*)?'
    setype: httpd_sys_content_t
    state: present
  register: set_selinux_context

# need to apply new contexts "now" to prevent potential issues in later tasks
- name: Apply new SELinux file context to filesystem # noqa no-handler no-changed-when
  ansible.builtin.command: restorecon -irv {{ mirror_path }}
  when: set_selinux_context.changed

- name: Create XFS filesystem for mirror data
  community.general.filesystem:
    state: present
    fstype: xfs
    force: false
    dev: "{{ mirror_dev_fs }}"
  tags:
    - bootstrap_mirror
  when: mirror_create_fs

- name: Add mirror FS to /etc/fstab
  ansible.posix.mount:
    path: "{{ mirror_path }}"
    src: "{{ mirror_dev }}"
    fstype: xfs
    state: mounted
  tags:
    - bootstrap_mirror
  when: mirror_create_fs

# only make sure the rsync *can* succeed, let the cron handle the full sync
- name: Bootstrap mirror # noqa command-instead-of-module
  ansible.builtin.command: "{{ item.bootstrap_command }}"
  args:
    creates: "{{ item.creates }}"
  changed_when: false
  loop: "{{ mirror_repos }}"
  tags:
    - bootstrap_mirror

- name: Setup cron for mirror
  ansible.builtin.cron:
    name: "{{ item.mirror_name }}"
    user: "{{ item.rsync_user | default('root') }}"
    minute: "{{ item.rsync_minute }}"
    hour: "{{ item.rsync_hour }}"
    job: "{{ item.rsync_command }}"
    cron_file: "{{ item.rsync_name }}"  # /etc/cron.d/almalinux_rsync
    state: "present"
  loop: "{{ mirror_repos }}"
  tags:
    - cron

- name: Customize sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value | string }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ mirror_sysctl_performance }}"
  tags:
    - sysctl

- name: Start/Enable Caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: started
    enabled: true
  tags:
    - caddy
