---
- name: User
  ansible.builtin.include_tasks: user.yml

- name: Set authorized_keys for root
  ansible.posix.authorized_key:
    user: "{{ almalinux_repo_deploy_user }}"
    state: present
    key: "{{ item }}"
    exclusive: true
  with_items:
    - "{{ almalinux_repo_ssh_authorized_keys }}"

- name: Create main directory
  ansible.builtin.file:
    path: "{{ almalinux_repo_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create repo directories
  ansible.builtin.file:
    path: "{{ almalinux_repo_dir }}{{ item.type }}/{{ item.repo }}"
    state: directory
    mode: '0755'
    owner: "{{ almalinux_repo_deploy_user }}"
    group: "{{ almalinux_repo_deploy_user }}"
  loop: "{{ almalinux_repo_dirs }}"

- name: Create repo bind mounts
  ansible.posix.mount:
    path: "{{ almalinux_repo_dir }}/{{ item.repo }}"
    src: "{{ almalinux_repo_dir }}{{ item.type }}/{{ item.repo }}"
    opts: bind
    state: mounted
    fstype: none
  loop: "{{ almalinux_repo_dirs }}"

- name: Allow http/https traffic through firewalld
  ansible.posix.firewalld:
    zone: public
    state: enabled
    permanent: true
    immediate: true
    service: "{{ item }}"
  loop:
    - http
    - https
  tags:
    - firewalld

- name: Customize sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value | string }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ almalinux_repo_sysctl_performance }}"
  tags:
    - sysctl

- name: SELinux
  ansible.builtin.include_tasks: selinux.yml

- name: Certbot
  ansible.builtin.include_tasks: certbot.yml

- name: Nginx
  ansible.builtin.include_tasks: nginx.yml

- name: Obtain SSL certificates
  ansible.builtin.include_tasks: certbot-obtain.yml

- name: Rsyncd
  ansible.builtin.include_tasks: rsyncd.yml

- name: Sync trigger fan-out
  ansible.builtin.include_tasks: sync-trigger.yml
  when: almalinux_repo_sync_trigger_enabled
  tags:
    - sync_trigger
