---
- name: Set SELinux context for content main content dir
  community.general.sefcontext:
    target: '{{ almalinux_repo_dir }}(/.*)?'
    setype: public_content_t
    state: present
  register: almalinux_repo_set_selinux_context
  tags:
    - caddy
    - rsyncd
    - selinux

- name: Set SELinux context for content subdirectories
  community.general.sefcontext:
    target: '{{ almalinux_repo_dir }}{{ item }}(/.*)?'
    setype: public_content_t
    state: present
  register: almalinux_repo_set_selinux_context
  tags:
    - caddy
    - rsyncd
    - selinux
  loop: "{{ almalinux_repo_dirs | map(attribute='type') | unique }}"

# need to apply new contexts "now" to prevent potential issues in later tasks
- name: Apply new SELinux file context to filesystem for content # noqa no-handler no-changed-when
  ansible.builtin.command: restorecon -irv {{ almalinux_repo_dir }} {{ almalinux_repo_dirs | map(attribute='type') | unique |
    map('regex_replace', '^', almalinux_repo_dir) | join(' ') }}
  when: almalinux_repo_set_selinux_context.changed
  tags:
    - caddy
    - rsyncd
    - selinux
