---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - git
    state: present

- name: Download gitea binary
  ansible.builtin.get_url:
    url: https://dl.gitea.com/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64
    dest: /usr/local/bin/gitea
    mode: "0755"

- name: Create system user
  ansible.builtin.user:
    name: git
    comment: Gitea user

- name: Create directory structure
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    mode: "0750"
    owner: git
    group: git
  loop:
    - /var/lib/gitea/custom
    - /var/lib/gitea/data
    - /var/lib/gitea/log
    - /etc/gitea

- name: Copy systemd service template
  ansible.builtin.template:
    src: gitea.service.j2
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Write Gitea conf
  ansible.builtin.template:
    src: app.ini.j2
    dest: /etc/gitea/app.ini
    mode: "0640"
    owner: git
    group: git
  notify: Restart Gitea

- name: Start gitea
  ansible.builtin.systemd_service:
    name: gitea
    state: started
    enabled: true

- name: Configure caddy reverse proxy
  ansible.builtin.include_tasks: caddy.yml
