#SPDX-License-Identifier: MIT-0
---
# defaults file for noggin
webserver: nginx
webserver_rootdoc: /var/www/html
#Used by firewalld rule
web_services:
  - http
  - https

#noggin vars
#Variables user for noggin installation
apply_noggin_install_workaround: True
noggin_temp_rpm_dir: /opt/noggin_rpms #This directory will be used to temporary download the rpms needed by noggin and manually installed because of a clash between nginx and noggin rpms

#Variables used for noggin web app configuration
freeipa_admin_user: adminuser
freeipa_admin_pass: changeme
freeipa_hosts:
 - host: freeipa1.atm.local
   port: 443
 - host: freeipa2.atm.local
   port: 443
freeipa_cert_dir: /etc/ipa
freeipa_ca_cert_file: ipa_ca.crt

# If set to False then noggin if properly configured will send email to the user, otw if set to True it will not send email because is suppressing then sending
noggin_mail_suppress_send: False
noggin_mail_server: smtp.gmail.com
noggin_mail_port: 587
noggin_use_tls: True
noggin_use_ssl: False
noggin_mail_username: myservice@email.com
noggin_mail_password: myserviceemailpassword
noggin_mail_default_sender: myservice@email.com
noggin_mail_debug: True
noggin_debug: True

#Variables user for noggin nginx configuration
ngnix_noggin_server_name: noggin.lab.local

nginx_noggin_enable_tls: True

noggin_private_key_dir: /etc/noggin/private-key
noggin_private_key_name: noggin-selfsigned.key
noggin_cert_dir: /etc/noggin/
noggin_cert_name: noggin-selfsigned.crt
