---
- name: Set server hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Install epel-release
  ansible.builtin.dnf:
    name: epel-release
    state: present
  tags:
    - repos

- name: Enable PowerTools on EL8
  ansible.builtin.yum_repository:
    name: powertools
    description: AlmaLinux $releasever - PowerTools
    mirrorlist: https://mirrors.almalinux.org/mirrorlist/$releasever/powertools
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
    enabled: true
  when: ansible_facts['distribution_major_version'] == "8"
  tags:
    - repos

- name: Enable CRB on EL9
  ansible.builtin.yum_repository:
    name: almalinux-crb
    description: AlmaLinux $releasever - CRB
    mirrorlist: https://mirrors.almalinux.org/mirrorlist/$releasever/crb
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
    enabled: true
  when: ansible_facts['distribution_major_version'] >= "9" # == 9?
  tags:
    - repos

- ansible.builtin.import_tasks: users.yml # noqa name[missing]
- ansible.builtin.import_tasks: firewalld.yml # noqa name[missing]
- ansible.builtin.import_tasks: packages.yml # noqa name[missing]
