---
- name: Add zabbix zone
  ansible.posix.firewalld:
    zone: zabbix
    state: present
    permanent: true
  notify:
    - reload firewalld
  tags:
    - firewalld
    - zabbix

- name: Allow zabbix traffic port 10050/tcp
  ansible.posix.firewalld:
    zone: zabbix
    state: enabled
    permanent: true
    port: 10050/tcp
  tags:
    - firewalld
    - zabbix

# Redundant from whitelist_ips in common/firewalld.yml
- name: Allow zabbix source traffic from Zabbix server
  ansible.posix.firewalld:
    zone: zabbix
    state: enabled
    permanent: true
    source: "{{ zabbix_server }}"
  tags:
    - firewalld
    - zabbix

- name: Install Zabbix repository
  ansible.builtin.dnf:
    name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
    state: present
    disable_gpg_check: true
  tags:
    - zabbix

# EPEL provides conflicting packages for some of the packages in the Zabbix repo
- name: Add zabbix* to EPEL excludepkgs
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/epel.repo
    line: 'excludepkgs=zabbix*'
    insertafter: '^\[epel\]$'
    state: present
  tags:
    - zabbix

- name: Install Zabbix agent
  ansible.builtin.package:
    name: zabbix-agent2
    state: present
  tags:
    - zabbix

- name: Distribute Zabbix configurations
  ansible.builtin.template:
    src: "etc/zabbix/{{ item }}.j2"
    dest: "/etc/zabbix/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "zabbix_agent2.conf"
    - "zabbix_agent2.d/almalinux.conf"
  notify:
    - Restart zabbix-agent2
  tags:
    - zabbix

- name: Enable/start zabbix-agent2
  ansible.builtin.systemd:
    name: zabbix-agent2.service
    state: started
    enabled: true
  tags:
    - zabbix
