---
- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Apply SELinux context to webroot
  ansible.builtin.command: restorecon -R {{ people_webroot }}
  changed_when: false
