---
# this is because the ipaclient role is not idempotent
- name: Check if IPA client installed
  ansible.builtin.stat:
    path: /etc/ipa/ca.crt
  register: ipa_client_installed

- name: Configure freeipa client
  vars:
    ipaclient_reinstall: "{{ lookup('env', 'IPACLIENT_REINSTALL') | default(false) }}" # noqa var-naming[no-role-prefix]
    state: present
  ansible.builtin.include_role:
    name: freeipa.ansible_freeipa.ipaclient
  when: not ipa_client_installed.stat.exists or ipaclient_reinstall

- name: Symlink IPA CA to trusted anchors
  ansible.builtin.file:
    src: /etc/ipa/ca.crt
    dest: /etc/pki/ca-trust/source/anchors/ipa-ca.crt
    owner: root
    group: root
    state: link
  register: ipa_client_symlink_ipa_ca

# can't use handler as we need this in later tasks
- name: Update CA Trust # noqa no-changed-when no-handler
  ansible.builtin.shell: update-ca-trust # noqa command-instead-of-shell
  when: ipa_client_symlink_ipa_ca.changed
