# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  pull_request:
  push:

env:
  # ansible_lint_version: v24.5.0
  python_version: 3.12 # must have an alma rpm available in format python<version>

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/checkout@v4

      - name: Install dnf dependencies
        shell: bash
        run: |
          dnf -y install ansible-core epel-release git-core python$python_version python$python_version-pip

      - name: Create and enter venv
        shell: bash
        run: |
          python$python_version -m venv /venv

      - name: Install ansible-lint
        shell: bash
        # if we need to version lock example:
        # pip3.12 install "ansible-lint[lock] @ git+https://github.com/ansible/ansible-lint@$ansible_lint_version"
        run: |
          /venv/bin/pip install "ansible-lint"
          /venv/bin/ansible-lint --version

      # for some reason ansible-lint in online mode does not grab all deps properly
      # this does
      - name: Install ansible-galaxy dependencies
        shell: bash
        run: |
          /venv/bin/ansible-galaxy install -r requirements.yml

      - name: Run ansible-lint
        shell: bash
        working-directory: ${{ github.workspace }}
        run: /venv/bin/ansible-lint --exclude ${HOME}/.ansible/roles/ --exclude ${HOME}/.ansible/collections/ --offline
